from django.db import models


# ---------------------------------------------------------------------------
# Role
# ---------------------------------------------------------------------------
# Mirrors: public.roles
# managed = False — table is owned by Supabase / PostgreSQL seed data.
# Django must NOT recreate or drop this table.
# ---------------------------------------------------------------------------
class Role(models.Model):
    """
    Maps to public.roles.
    Stores the five system roles (citizen, ground_level_employee, supervisor,
    department_admin, system_admin).
    """

    CITIZEN = 'citizen'
    GROUND_LEVEL_EMPLOYEE = 'ground_level_employee'
    SUPERVISOR = 'supervisor'
    DEPARTMENT_ADMIN = 'department_admin'
    SYSTEM_ADMIN = 'system_admin'

    ROLE_CHOICES = [
        (CITIZEN, 'Citizen'),
        (GROUND_LEVEL_EMPLOYEE, 'Ground-Level Employee'),
        (SUPERVISOR, 'Supervisor'),
        (DEPARTMENT_ADMIN, 'Department Admin'),
        (SYSTEM_ADMIN, 'System Admin'),
    ]

    # PK is a smallint identity in the DB schema.
    id = models.SmallAutoField(primary_key=True)
    role_name = models.CharField(max_length=64, unique=True, choices=ROLE_CHOICES)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=False)

    class Meta:
        managed = False
        db_table = 'roles'

    def __str__(self):
        return self.role_name


# ---------------------------------------------------------------------------
# Department
# ---------------------------------------------------------------------------
# Mirrors: public.departments
# managed = False — table lives in Supabase and is managed there.
# ---------------------------------------------------------------------------
class Department(models.Model):
    """
    Maps to public.departments.
    Government departments/offices that handle complaint categories.
    """

    id = models.UUIDField(primary_key=True)
    name = models.TextField(unique=True)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'departments'

    def __str__(self):
        return self.name


# ---------------------------------------------------------------------------
# Profile
# ---------------------------------------------------------------------------
# Mirrors: public.profiles
# managed = False — profiles are created by a Supabase DB trigger on
#   auth.users INSERT.  Django reads/updates profiles; it does NOT create them.
# ---------------------------------------------------------------------------
class Profile(models.Model):
    """
    Maps to public.profiles.
    Extends Supabase Auth (auth.users) with application-level user data.

    id must equal the auth.users UUID — Supabase is the identity source of truth.
    """

    ACCOUNT_STATUS_ACTIVE = 'active'
    ACCOUNT_STATUS_INACTIVE = 'inactive'
    ACCOUNT_STATUS_PENDING = 'pending_verification'

    ACCOUNT_STATUS_CHOICES = [
        (ACCOUNT_STATUS_ACTIVE, 'Active'),
        (ACCOUNT_STATUS_INACTIVE, 'Inactive'),
        (ACCOUNT_STATUS_PENDING, 'Pending Verification'),
    ]

    # Matches auth.users.id — Supabase UUID, not auto-generated by Django.
    id = models.UUIDField(primary_key=True)
    full_name = models.TextField()
    email = models.TextField(unique=True, null=True, blank=True)
    phone = models.TextField(unique=True, null=True, blank=True)

    # FK → roles(id)
    role = models.ForeignKey(
        Role,
        on_delete=models.PROTECT,
        db_column='role_id',
        related_name='profiles',
    )

    # FK → departments(id) — NULL for citizens and system admins.
    department = models.ForeignKey(
        Department,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        db_column='department_id',
        related_name='profiles',
    )

    # FK → jurisdictions(id) — Nullable for citizens, required for supervisors in specific districts.
    jurisdiction = models.ForeignKey(
        'departments.Jurisdiction',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        db_column='jurisdiction_id',
        related_name='profiles',
    )

    # Self-referential FK — ground-level employees may reference a supervisor.
    supervisor = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        db_column='supervisor_id',
        related_name='subordinates',
    )

    account_status = models.CharField(
        max_length=32,
        choices=ACCOUNT_STATUS_CHOICES,
        default=ACCOUNT_STATUS_PENDING,
    )
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'profiles'

    def __str__(self):
        return f'{self.full_name} ({self.role.role_name})'

    # ------------------------------------------------------------------
    # Convenience role-check properties
    # ------------------------------------------------------------------

    @property
    def role_name(self) -> str:
        return self.role.role_name

    @property
    def is_citizen(self) -> bool:
        return self.role_name == Role.CITIZEN

    @property
    def is_ground_level_employee(self) -> bool:
        return self.role_name == Role.GROUND_LEVEL_EMPLOYEE

    @property
    def is_supervisor(self) -> bool:
        return self.role_name == Role.SUPERVISOR

    @property
    def is_department_admin(self) -> bool:
        return self.role_name == Role.DEPARTMENT_ADMIN

    @property
    def is_system_admin(self) -> bool:
        return self.role_name == Role.SYSTEM_ADMIN

    @property
    def is_staff_member(self) -> bool:
        """True for any non-citizen role."""
        return self.role_name != Role.CITIZEN

    def shares_department_with(self, other_profile: 'Profile') -> bool:
        """
        Returns True when both profiles belong to the same department.
        Used to enforce the department-boundary rule server-side.
        """
        if self.department_id is None or other_profile.department_id is None:
            return False
        return self.department_id == other_profile.department_id


# ---------------------------------------------------------------------------
# UserPermission
# ---------------------------------------------------------------------------
# Mirrors: public.user_permissions
# managed = False — optional per-user permission overrides stored in Supabase.
# ---------------------------------------------------------------------------
class UserPermission(models.Model):
    """
    Maps to public.user_permissions.
    Optional per-user permission overrides on top of role-based access.
    """

    id = models.UUIDField(primary_key=True)
    user = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        db_column='user_id',
        related_name='permissions',
    )
    permission_key = models.TextField()
    is_granted = models.BooleanField(default=True)
    modified_by = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        db_column='modified_by',
        related_name='granted_permissions',
    )
    modified_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'user_permissions'
        unique_together = [('user', 'permission_key')]

    def __str__(self):
        return f'{self.user_id} / {self.permission_key} = {self.is_granted}'


# ---------------------------------------------------------------------------
# AuditLog
# ---------------------------------------------------------------------------
# Mirrors: public.audit_logs
# managed = False - application audit trail
# ---------------------------------------------------------------------------
class AuditLog(models.Model):
    """
    Maps to public.audit_logs.
    General administrative audit trail.
    """

    id = models.BigAutoField(primary_key=True)
    actor = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        db_column='actor_id',
        related_name='audit_actions',
    )
    action = models.TextField()
    entity_type = models.TextField()
    entity_id = models.TextField(null=True, blank=True)
    old_value = models.JSONField(null=True, blank=True)
    new_value = models.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'audit_logs'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.actor_id} {self.action} {self.entity_type} {self.entity_id}"
