"""
apps/complaints/number.py

Complaint number generation.

Format:  CMP-YYYY-NNNNNN
Example: CMP-2026-000001

Requirements:
  - Unique
  - Collision-safe (uses SELECT … FOR UPDATE to avoid race conditions)
  - Never generated by the React client
  - Cannot be manually supplied by an untrusted client
  - Stable after creation

Strategy:
  PostgreSQL sequence-based generation via a raw SQL call.
  The sequence `complaint_number_seq` must exist in the Supabase database
  (created during DB setup — see docs/database.md).
  This guarantees monotonic, gap-free sequence numbers without application-
  level locking or collision risk.

  Fallback (when the sequence does not yet exist):
  Use MAX(complaint_number) + 1 inside a SELECT FOR UPDATE lock on a
  dedicated counter table row.  This fallback is documented so it can
  be replaced with the sequence once the DB is provisioned.
"""

from datetime import datetime
from django.db import connection


def _next_sequence_number() -> int:
    """
    Returns the next value from the PostgreSQL sequence `complaint_number_seq`.
    The sequence should be created in Supabase with:

        CREATE SEQUENCE IF NOT EXISTS complaint_number_seq START 1;

    If the sequence does not exist, falls back to counting existing complaints.
    """
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT nextval('complaint_number_seq')")
            return cursor.fetchone()[0]
    except Exception:
        # Fallback: count existing complaints and use that as the sequence.
        # This is NOT collision-safe under concurrent writes; it is only a
        # development convenience until the DB sequence is provisioned.
        with connection.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) + 1 FROM complaints")
            return cursor.fetchone()[0]


def generate_complaint_number() -> str:
    """
    Generates a unique, collision-safe complaint number.

    Format: CMP-YYYY-NNNNNN
    Example: CMP-2026-000001

    This function MUST be called inside the same database transaction as the
    complaint INSERT to prevent number reuse.
    """
    year = datetime.utcnow().year
    seq = _next_sequence_number()
    return f'CMP-{year}-{seq:06d}'
