# Generated by Django 5.1.1 on 2026-08-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE public.complaint_categories 
                ADD COLUMN IF NOT EXISTS base_priority varchar(16) NOT NULL DEFAULT 'medium';
                
                UPDATE public.complaint_categories SET base_priority = 'high' WHERE name IN ('drainage', 'garbage', 'pothole', 'road_damage', 'sanitation', 'water_supply');
                UPDATE public.complaint_categories SET base_priority = 'medium' WHERE name IN ('other', 'streetlight');
            """,
            reverse_sql="""
                ALTER TABLE public.complaint_categories 
                DROP COLUMN IF EXISTS base_priority;
            """
        )
    ]
