# Generated by Django 5.1.1 on 2026-08-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationReviewTask",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_review", "In Review"),
                            ("completed", "Completed"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("review_remarks", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "classification_review_tasks",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("complaint_number", models.TextField(unique=True)),
                ("description", models.TextField()),
                ("location", models.TextField()),
                ("location_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("location_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("location_address", models.TextField(blank=True, null=True)),
                ("district", models.TextField(blank=True, null=True)),
                ("state", models.TextField(blank=True, null=True)),
                ("google_maps_url", models.TextField(blank=True, null=True)),
                ("taluk", models.TextField(blank=True, null=True)),
                ("local_body", models.TextField(blank=True, null=True)),
                ("ward", models.TextField(blank=True, null=True)),
                ("inconvenience_details", models.TextField(blank=True, null=True)),
                ("expected_solution", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_verification", "Under Verification"),
                            ("assigned", "Assigned"),
                            ("verified", "Verified"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("invalid", "Invalid"),
                        ],
                        default="submitted",
                        max_length=32,
                    ),
                ),
                (
                    "priority_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "priority_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "severity_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("reporter_count", models.IntegerField(default=1)),
                ("expected_completion_date", models.DateField(blank=True, null=True)),
                (
                    "closure_confirmation",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("auto_closed", "Auto Closed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("closure_due_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "complaints",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ComplaintAssignment",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("assignment_reason", models.TextField(blank=True, null=True)),
                ("assignment_date", models.DateTimeField()),
                ("reassignment_reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "complaint_assignments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ComplaintAttachment",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("file_path", models.TextField()),
                ("file_url", models.TextField(blank=True, null=True)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        max_length=16,
                    ),
                ),
                ("mime_type", models.TextField(blank=True, null=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("submission_evidence", "Submission Evidence"),
                            ("verification_evidence", "Verification Evidence"),
                            ("resolution_proof", "Resolution Proof"),
                        ],
                        max_length=32,
                    ),
                ),
                ("uploaded_at", models.DateTimeField()),
            ],
            options={
                "db_table": "complaint_attachments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ComplaintCategory",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("requires_attachment", models.BooleanField(default=False)),
                (
                    "base_priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "complaint_categories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ComplaintClassification",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "severity_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("model_name", models.TextField(blank=True, null=True)),
                ("model_version", models.TextField(blank=True, null=True)),
                ("is_manual_override", models.BooleanField(default=False)),
                ("classified_at", models.DateTimeField()),
            ],
            options={
                "db_table": "complaint_classifications",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ComplaintResolution",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("progress_update", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("expected_completion_date", models.DateField(blank=True, null=True)),
                ("resolution_details", models.TextField(blank=True, null=True)),
                ("resolution_proof_url", models.TextField(blank=True, null=True)),
                ("is_final_resolution", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "complaint_resolutions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ComplaintStatusHistory",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_verification", "Under Verification"),
                            ("assigned", "Assigned"),
                            ("verified", "Verified"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("invalid", "Invalid"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_verification", "Under Verification"),
                            ("assigned", "Assigned"),
                            ("verified", "Verified"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("invalid", "Invalid"),
                        ],
                        max_length=32,
                    ),
                ),
                ("change_reason", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "complaint_status_history",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ComplaintVerification",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("site_inspection_notes", models.TextField(blank=True, null=True)),
                (
                    "verification_result",
                    models.CharField(
                        choices=[("verified", "Verified"), ("invalid", "Invalid")],
                        max_length=16,
                    ),
                ),
                ("verification_remarks", models.TextField()),
                ("verified_at", models.DateTimeField()),
            ],
            options={
                "db_table": "complaint_verifications",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("submission", "Submission"),
                            ("classification", "Classification"),
                            ("verification", "Verification"),
                            ("assignment", "Assignment"),
                            ("status_change", "Status Change"),
                            ("deadline_change", "Deadline Change"),
                            ("resolution", "Resolution"),
                            ("closure", "Closure"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "In App"),
                        ],
                        default="in_app",
                        max_length=16,
                    ),
                ),
                ("message_content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("delivery_attempts", models.IntegerField(default=0)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "notifications",
                "managed": False,
            },
        ),
    ]
